package rand

import (
	"crypto/rand"
	"encoding/base64"
)

const RememberTokenBytes = 32

//helper function designed to generate remember tokens of a predetermined byte size
func RememberToken() (string, error) {
	return String(RememberTokenBytes)
}

//bytes will help us generate n random bytes 
func Bytes(n int) ([]byte, error) {
	b := make([]byte, n)
	_, err := rand.Read(b)
	if err != nil {
		return nil, err
	}
	return b, nil
}

//string will generate  a byte if slice size nBytes and then return a string that is the base64 URL encoded version.
func String(nBytes int) (string, error) {
	b, err := Bytes(nBytes)
	if err != nil {
		return "", err
	}
	return base64.URLEncoding.EncodeToString(b), nil
}

//Nbytes returns a number of bytes used in any string generated by the String or RememberToken functions in this package.
func NBytes(base64String string) (int, error) {
	b, err := base64.RawStdEncoding.DecodeString(base64String)
	if err != nil {
		return -1, err
	}
	return len(b), nil
}